# MIT License
# Copyright (c) 2024 [SNALE - French SAS Company - RCS 951 724 616]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "configbuilder"
version = "0.1.0"
requires-python = ">=3.9"
authors = [
  {name = "Fabien RÉTIF", email = "fabien.retif@snale.net"},
]
description = " "
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]

dependencies = [
    "configbuilder-core==0.0.1",
]
packages = []

[project.urls]
Homepage = "https://lab.snale.net/"
Documentation = " "
Repository = "https://github.com/snale-net/config-builder"

[tool.setuptools.packages.find]
exclude = ["configbuilder.providers","configbuilder.providers.*","*.tests", "*.tests.*", "tests.*", "tests"]

[project.optional-dependencies]
"swan" = [
    "configbuilder-providers-swan"
]
"ww3" = [
    "configbuilder-providers-ww3"
]
"all" = [
    "configbuilder-providers-swan",  
    "configbuilder-providers-ww3",
]


## pytest settings ##
[tool.pytest.ini_options]
# We need to make sure configbuilder-core sources are first in the pythonpath, because uv sync adds sources to
# pythonpath in basically random order and pytest does not understand legacy namespace packages and cannot
# use namespace packages effectively when collecting tests.
pythonpath = [
    "configbuilder-core"
]
testpaths = [
    "tests",
]
asyncio_default_fixture_loop_scope = "function"
log_cli = true
log_cli_level = "DEBUG"

[tool.uv.sources]
# These names must match the names as defined in the pyproject.toml of the workspace items,
# *not* the workspace folder paths
configbuilder = {workspace = true}
configbuilder-core = {workspace = true}
configbuilder-providers-swan = {workspace = true}
configbuilder-providers-ww3 = {workspace = true}

[tool.uv.workspace]
members = [
    ".",
    "configbuilder-core",
    "providers/swan",
    "providers/ww3",
]
